config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :suites
    resources :colleges
    resources :buildings
    resources :draws
    resources :groups
    resources :memberships
    resources :rooms

    root to: 'users#index'
  end

  devise_for :users
  unauthenticated :user do
    root to: 'high_voltage/pages#show', id: 'home', as: 'landing_page'
  end
  root to: 'dashboards#show'

  resources :colleges, only: %i(index new create show edit update)

  shallow do
    resources :buildings do
      resources :suites, except: :index do
        member do
          get 'merge'
          post 'merge', to: 'suites#perform_merge'
          get 'split'
          post 'split', to: 'suites#perform_split'
          post 'unmerge'
        end
        resources :rooms, except: :index
      end
    end
  end

  post 'suite_import/import', to: 'suite_imports#import', as: 'suite_import'

  resource :terms_of_service, only: %i(show) do
    patch 'accept'
  end

  resources :users do
    member do
      get 'intent', to: 'users#edit_intent', as: 'edit_intent'
      patch 'intent', to: 'users#update_intent', as: 'update_intent'
    end

    collection do
      get 'build'
    end
  end

  resources :enrollments, only: %i(new create)

  resources :draws do
    member do
      patch 'activate'
      post 'reminder'
      patch 'bulk_on_campus'
      get 'students', to: 'draws#student_summary', as: 'student_summary'
      patch 'students', to: 'draws#students_update', as: 'students_update'
      get 'lottery_confirmation'
      patch 'start_lottery'
      get 'oversubscription', to: 'draws#oversubscription', as: 'oversub'
      patch 'size_lock/:size', to: 'draws#toggle_size_lock',
                               as: 'toggle_size_lock'
      patch 'lock_all_sizes'
      delete 'prune_oversub/:prune_size', to: 'draws#prune', as: 'prune'
      patch 'start_selection'
      get 'results'
      get 'group_export'
    end

    resources :draw_suites, only: %i(index), as: :suites do
      collection do
        get 'edit_collection'
        patch 'update_collection'
      end
    end

    resources :lottery_assignments, only: %i(update create index) do
      collection do
        post 'automatic'
      end
    end

    resources :groups do
      member do
        post 'request', to: 'groups#request_to_join'
        put 'accept_request'
        get 'invite'
        patch 'invite', to: 'groups#send_invites', as: 'send_invites'
        put 'accept_invitation'
        put 'reject_pending'
        put 'finalize'
        put 'finalize_membership'
        put 'lock'
        put 'unlock'
        delete 'leave'
        patch 'make_drawless'
      end
      collection do
        resource :suite_assignment, only: %i(new create destroy)
      end
    end

    resource :clip, only: %i(new create)

    resource :intents, only: [] do
      get 'report'
      post 'import'
      get 'export'
    end
  end

  resources :clips, only: %i(show edit update destroy)

  resources :clip_memberships, only: %i(update destroy)

  resources :groups, controller: 'drawless_groups' do
    member do
      put 'lock'
      put 'unlock'
    end
    resource :suite_assignment, only: %i(new create destroy)
    resource :room_assignment, only: %i(new create edit) do
      collection do
        get 'confirm'
      end
    end
  end

  resource :email_export, only: %i(new create)

  resources :results, only: [] do
    collection do
      get 'students'
      get 'suites'
      get 'export'
    end
  end
end

app/models/suite.rb
# frozen_string_literal: true

# Model to represent the middle level of facility information
# A suite is composed of mulitple rooms, which can be bedrooms or common rooms
#
# @attr [String] number The identifier of the Suite. Must be unique
#   for Suites in the same Building.
# @attr [Integer] size Counter cache of the total number of beds
#   within the Suite's Rooms. Must be >= 0.
# @attr [Building] building belongs_to association for the Building the
#   Suite is located in.
# @attr [Array<Room>] rooms has_many association for the Rooms within the Suite.
class Suite < ApplicationRecord
  SIZE_STRS = { 1 => 'single', 2 => 'double', 3 => 'triple', 4 => 'quad',
                5 => 'quint', 6 => 'sextet', 7 => 'septet',
                8 => 'octet', 0 => 'empty' }.freeze
  belongs_to :building
  belongs_to :group
  has_many :rooms, dependent: :nullify
  has_many :draw_suites, dependent: :delete_all
  has_many :draws, through: :draw_suites

  validates :building, presence: true
  validates :number, presence: true, uniqueness: { scope: :building }
  validates :size, presence: true,
                   numericality: { greater_than_or_equal_to: 0 }

  scope :available, -> { where(group_id: nil) }

  before_save :clear_room_ids, if: ->() { will_save_change_to_group_id? }
  before_save :remove_draw_from_medical_suites,
              if: ->() { will_save_change_to_medical? }
  after_save :update_lottery_assignment, if: ->() { saved_change_to_group_id? }

  # Return the equivalent string for a given suite size
  #
  # @param size [Integer] the suite size
  # @return [String] the equivalnet string
  def self.size_str(size)
    raise ArgumentError unless size.is_a?(Integer) && size >= 0
    return SIZE_STRS[size] if SIZE_STRS.key? size
    "#{size}-pack"
  end

  # Return the building name with the suite number
  #
  # @return [String] the building name with the suite number
  def name
    "#{building.name} #{number}"
  end

  # Return the building name with the suite number and the medical status
  #
  # @return [String] the building name with the suite number and medical status
  def name_with_medical
    return name unless medical
    "#{name} (medical)"
  end

  # Return the name of the suite with the names of any draws it belongs to.
  # Optionally excludes a single draw passed in.
  #
  # @param [Draw] the draw to exclude
  # @return [String] the suite name with draw names
  def name_with_draws(draw = nil)
    return name if draws.empty?
    draws_to_display = draws.where.not(id: draw&.id)
    return name if draws_to_display.empty?
    draws_str = draws_to_display.map(&:name).join(', ')
    "#{name} (#{draws_str})"
  end

  # Return whether or not a suite is available
  #
  # @return [Boolean] whether or not the suite is available
  def available?
    group_id.nil?
  end

  # Return all single-bed rooms in the suite
  #
  # @return [Room::ActiveRecord_AssociationRelation] relation for all of the
  #   rooms with 1 bed
  def singles
    rooms.select { |r| r.beds == 1 }
  end

  # Return all double-bed rooms in the suite
  #
  # @return [Room::ActiveRecord_AssociationRelation] relation for all of the
  #   rooms with 2 bed
  def doubles
    rooms.select { |r| r.beds == 2 }
  end

  # Return all common rooms in the suite
  #
  # @return [Room::ActiveRecord_AssociationRelation] relation for all of the
  #   common rooms
  def common_rooms
    rooms.select { |r| r.beds.zero? }
  end

  # Return whether or not a suite can be selected in a new draw (e.g. it is not
  # currently in any draw that is in the lottery or suite_selection phase)
  #
  # @return [Boolean] whether or not the suite is selectable
  def selectable?
    draws.all? { |draw| !(draw.lottery? || draw.suite_selection?) }
  end

  # Return the suite number, indicating if the suite is a medical suite or not
  #
  # @return [String] the number with medical status indicated
  def number_with_medical
    return number unless medical
    "#{number} (medical)"
  end

  private

  def clear_room_ids
    id_array = group_id_change_to_be_saved.compact
    members = User.includes(:group).where(groups: { id: id_array })
    ActiveRecord::Base.transaction { members.update(room_id: nil) }
  rescue
    throw(:abort)
  end

  def remove_draw_from_medical_suites
    return unless medical
    ActiveRecord::Base.transaction { draws.delete_all }
  rescue
    throw(:abort)
  end

  def update_lottery_assignment
    g_id = saved_change_to_group_id.compact.first
    lottery = Group.includes(:lottery_assignment).find(g_id).lottery_assignment
    return unless lottery
    lottery.update_selected!
  end
end

app/controllers/admin/suites_controller.rb
# frozen_string_literal: true

module Admin
  class SuitesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Suite.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Suite.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/suites_controller.rb
# frozen_string_literal: true

# Controller for Suites
class SuitesController < ApplicationController
  prepend_before_action :set_suite, except: %i(new create index)
  prepend_before_action :set_building, only: %i(new create)

  def show
    @rooms = @suite.rooms.order(:number)
    @draws = @suite.draws
    @building = @suite.building
    @group = @suite.group
    @merger_form = SuiteMergerForm.new(suite: @suite)
  end

  def new
    @suite = Suite.new
  end

  def create
    result = Creator.create!(klass: Suite, params: suite_params,
                             name_method: :number)
    @suite = result[:record]
    handle_action(action: 'new', **result)
  end

  def edit; end

  def update
    result = Updater.update(object: @suite, params: suite_params,
                            name_method: :number)
    @suite = result[:record]
    handle_action(action: 'edit', **result)
  end

  def destroy
    result = Destroyer.new(object: @suite, name_method: :number).destroy
    handle_action(path: building_path(@suite.building), **result)
  end

  def merge
    @merger_form = SuiteMergerForm.new(suite: @suite,
                                       params: suite_merger_params)
    unless @merger_form.valid?
      flash[:error] = 'Invalid suite number'
      redirect_to(suite_path(@suite)) && return
    end
    @other_suite = @merger_form.other_suite
    @all_rooms = @suite.rooms + @merger_form.other_suite.rooms
  end

  def perform_merge
    result = SuiteMergerForm.submit(suite: @suite, params: suite_merger_params)
    @merger_form = result[:form_object] if result[:form_object]
    @all_rooms = find_merger_rooms if @merger_form
    handle_action(action: 'merge', **result)
  end

  def split
    @split_form = SuiteSplitForm.new(suite: @suite)
  end

  def perform_split
    result = SuiteSplitForm.submit(suite: @suite, params: suite_split_params)
    @split_form = result[:form_object] if result[:form_object]
    handle_action(path: building_path(@suite.building), **result)
  end

  def unmerge
    result = SuiteUnmerger.unmerge(suite: @suite)
    handle_action(**result)
  end

  private

  def authorize!
    if @suite
      authorize @suite
    else
      authorize Suite
    end
  end

  def suite_params
    params.require(:suite).permit(:number, :building_id, :medical)
  end

  def suite_merger_params
    params.require(:suite_merger_form).permit(:number, :other_suite_number)
  end

  def suite_split_params
    valid_params = @suite.rooms.map { |r| "room_#{r.id}_suite".to_sym }
    params.require(:suite_split_form).permit(*valid_params)
  end

  def set_suite
    @suite = Suite.includes(:rooms).find(params[:id])
  end

  def set_building
    @building = Building.find(params[:building_id])
  end

  def find_merger_rooms
    id_array = [@suite.id, @merger_form.other_suite.id]
    Room.includes(:suite).where(suites: { id: id_array })
  end
end

app/helpers/suites_helper.rb
# frozen_string_literal: true

# Helper module for Suites
module SuitesHelper
  # Returns the button string for the medical suite "form"
  #
  # @param suite [Suite] the suite in question
  # @return [String] the button string
  def medical_btn_str(suite)
    "Make #{medical_str(!suite.medical)}"
  end

  # Returns a suite describing a suite based on its medical flag
  #
  # @param medical [Boolean] whether or not the suite is a medical suite
  # @return [String] the string describing it
  def medical_str(medical)
    prefix = medical ? '' : 'non-'
    "#{prefix}medical suite"
  end
end

app/views/suites/_draw_link.html.erb
<%= link_to draw_link.name, draw_path(draw_link) %>

app/views/suites/_form.html.erb
<%= simple_form_for [@building, @suite] do |f| %>
  <%= f.input :number %>
  <% if @building %>
    <%= f.hidden_field :building_id, value: @building.id %>
  <% else %>
    <%= f.association :building %>
  <% end %>
  <%= f.input :medical, label: 'Medical suite' %>
  <%= f.submit %>
<% end %>

app/views/suites/_medical_form.html.erb
<%= simple_form_for suite, html: { class: 'hidden-form' } do |f| %>
  <%= f.input :medical, as: :hidden, input_html: { value: !suite.medical } %>
  <%= f.submit medical_btn_str(suite), class: 'primary' %>
<% end %>

app/views/suites/_size_link.html.erb
<a href="#suites-<%= size_str(size_link).pluralize %>"><%= headerize_size(size_link) %></a>

app/views/suites/_summary.html.erb
<% sizes.each do |size| %>
  <% next if suites[size].empty? %>
  <div class="suites-list" id="suites-<%= size_str(size).pluralize %>">
    <h3><%= headerize_size(size) %></h3>
    <p><%= render partial: 'suites/size_link', collection: sizes.select { |s| s != size }, spacer_template: 'shared/slash' %></p>
    <% unless suites[size].empty? %>
      <table>
        <thead>
          <tr>
            <td>#</td>
            <td># Singles</td>
            <td># Doubles</td>
            <td># Common</td>
            <td>Draws</td>
            <td></td>
          </tr>
        </thead>
        <tbody>
          <% suites[size].each do |suite| %>
            <% next if suite.medical && !policy(suite).medical? %>
            <tr id="suite-<%= suite.id %>">
              <td data-role="suite-number"><%= link_to suite.send(label_method), suite_path(suite) %></td>
              <td data-role="suite-singles"><%= suite.singles.count %></td>
              <td data-role="suite-doubles"><%= suite.doubles.count %></td>
              <td data-role="suite-common"><%= suite.common_rooms.count %></td>
              <td data-role="suite-draws">
                <%= render partial: 'suites/draw_link', collection: suite.draws, spacer_template: 'shared/comma' %>
              </td>
              <td class="actions" data-role="suite-actions">
                <%= link_to 'View', suite_path(suite), class: 'button' %>
                <% if policy(suite).edit? %>
                  <%= link_to 'Edit', edit_suite_path(suite), class: 'button' %>
                <% end %>
                <% if policy(suite).destroy? %>
                  <%= link_to 'Delete', suite_path(suite), method: :delete, data: { confirm: 'Are you sure you want to delete this suite?' }, class: 'button alert' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
<% end %>

app/views/suites/edit.html.erb
<% provide(:title, "Edit Suite #{@suite.number}") %>
<h1>Edit Suite <%= @suite.number %></h1>
<%= render "form", suite: @suite %>
<%= link_to 'Cancel', suite_path(@suite) %>

app/views/suites/merge.html.erb
<% provide(:title, "Merge Suites #{@suite.number} and #{@other_suite.number}") %>
<h1>Merge Suites <%= @suite.number %> and <%= @other_suite.number %></h1>
<%= simple_form_for @merger_form, url: merge_suite_path(@suite), method: :post do |f| %>
  <%= f.input :number %>
  <%= f.input :other_suite_number, as: :hidden  %>
  <p>The new suite will contain the following rooms:</p>
  <ul>
    <% @all_rooms.each do |room| %>
      <li><%= room.number %> - <%= pluralize(room.beds, 'bed') %></li>
    <% end %>
  </ul>
  <%= f.submit 'Merge' %>
<% end %>
<%= link_to 'Cancel', suite_path(@suite) %>

app/views/suites/new.html.erb
<% provide(:title, 'Add Suite') %>
<h1>Add Suite</h1>
<%= render "form", suite: @suite %>
<%= link_to 'Cancel', building_path(@building) %>

app/views/suites/show.html.erb
<% provide(:title, "Suite #{@suite.number}") %>
<h1 class="suite-number">Suite <%= @suite.number %></h1>
<% if policy(@suite).medical? %>
  <span class="label secondary suite-medical" style="margin-bottom: 1em;"><%= medical_str(@suite.medical).capitalize %></span>
<% end %>
<ul>
  <li>Status:
    <% if @suite.available? %>
      Available
    <% else %>
      Unavailable
      <% if !@suite.medical || policy(@suite).medical? %>
        (Assigned to <%= link_to @group.name, group_path(@group) %>)
      <% end %>
    <% end %>
  </li>
  <li>Size: <%= size_str(@suite.size).capitalize %></li>
  <li>Building: <%= link_to @building.name, building_path(@building) %></li>
  <li>Draws:
    <% if @draws.empty? %>
      None
    <% else %>
      <%= render partial: 'draw_link', collection: @draws, spacer_template: 'shared/comma' %>
    <% end %>
  </li>
</ul>
<h2 class="h3">Rooms</h2>
<%= render 'rooms/summary', rooms: @rooms %>
<p><%= link_to 'Add room', new_suite_room_path(@suite), class: 'button secondary' if policy(Room).new? %></p>
<hr />
<% if policy(@suite).merge? %>
  <div class="suite-merging">
    <h2>Merge suites</h2>
    <p>Please enter a suite to merge with this one; <b>it must be in the same building</b>. The two suites will be removed from Vesta and will be replaced with a single suite containing all of their rooms. You will able to set the name/number of the new suite on the following page.</p>
    <%= simple_form_for @merger_form, url: merge_suite_path(@suite), method: :get do |f| %>
      <%= f.input :other_suite_number, label: 'Other suite' %>
      <%= f.submit 'Merge' %>
    <% end %>
  </div>
<% end %>
<hr />
<% if policy(@suite).unmerge? %>
  <p><%= link_to 'Unmerge suite', unmerge_suite_path(@suite), class: 'button', method: :post %></p>
<% end %>
<% if policy(@suite).split? %>
  <p><%= link_to 'Split suite', split_suite_path(@suite), class: 'button' %></p>
<% end %>
<div>
  <% if policy(@suite).edit? %>
    <%= link_to 'Edit', edit_suite_path(@suite), class: 'button secondary' %>
  <% end %>
  <% if policy(@suite).medical? %>
    <%= render 'medical_form', suite: @suite %>
  <% end %>
  <% if policy(@suite).destroy? %>
    <%= link_to 'Delete', suite_path(@suite), method: :delete, data: { confirm: 'Are you sure you want to delete this suite?' }, class: 'button alert' %>
  <% end %>
</div>
<%= link_to 'Return to building', building_path(@building) %>

app/views/suites/split.html.erb
<% provide(:title, "Split Suite #{@suite.number}") %>
<h1>Split Suite <%= @suite.number%></h1>
<%= simple_form_for @split_form, url: split_suite_path(@suite), method: :post do |f| %>
  <% @suite.rooms.each do |room| %>
    <%= f.input "room_#{room.id}_suite".to_sym,
      label: "#{room.number} (#{room.type}) new suite" %>
  <% end %>
  <%= f.submit 'Split suite' %>
<% end %>
<p><%= link_to 'Cancel', suite_path(@suite) %>