config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :suites
    resources :colleges
    resources :buildings
    resources :draws
    resources :groups
    resources :memberships
    resources :rooms

    root to: 'users#index'
  end

  devise_for :users
  unauthenticated :user do
    root to: 'high_voltage/pages#show', id: 'home', as: 'landing_page'
  end
  root to: 'dashboards#show'

  resources :colleges, only: %i(index new create show edit update)

  shallow do
    resources :buildings do
      resources :suites, except: :index do
        member do
          get 'merge'
          post 'merge', to: 'suites#perform_merge'
          get 'split'
          post 'split', to: 'suites#perform_split'
          post 'unmerge'
        end
        resources :rooms, except: :index
      end
    end
  end

  post 'suite_import/import', to: 'suite_imports#import', as: 'suite_import'

  resource :terms_of_service, only: %i(show) do
    patch 'accept'
  end

  resources :users do
    member do
      get 'intent', to: 'users#edit_intent', as: 'edit_intent'
      patch 'intent', to: 'users#update_intent', as: 'update_intent'
    end

    collection do
      get 'build'
    end
  end

  resources :enrollments, only: %i(new create)

  resources :draws do
    member do
      patch 'activate'
      post 'reminder'
      patch 'bulk_on_campus'
      get 'students', to: 'draws#student_summary', as: 'student_summary'
      patch 'students', to: 'draws#students_update', as: 'students_update'
      get 'lottery_confirmation'
      patch 'start_lottery'
      get 'oversubscription', to: 'draws#oversubscription', as: 'oversub'
      patch 'size_lock/:size', to: 'draws#toggle_size_lock',
                               as: 'toggle_size_lock'
      patch 'lock_all_sizes'
      delete 'prune_oversub/:prune_size', to: 'draws#prune', as: 'prune'
      patch 'start_selection'
      get 'results'
      get 'group_export'
    end

    resources :draw_suites, only: %i(index), as: :suites do
      collection do
        get 'edit_collection'
        patch 'update_collection'
      end
    end

    resources :lottery_assignments, only: %i(update create index) do
      collection do
        post 'automatic'
      end
    end

    resources :groups do
      member do
        post 'request', to: 'groups#request_to_join'
        put 'accept_request'
        get 'invite'
        patch 'invite', to: 'groups#send_invites', as: 'send_invites'
        put 'accept_invitation'
        put 'reject_pending'
        put 'finalize'
        put 'finalize_membership'
        put 'lock'
        put 'unlock'
        delete 'leave'
        patch 'make_drawless'
      end
      collection do
        resource :suite_assignment, only: %i(new create destroy)
      end
    end

    resource :clip, only: %i(new create)

    resource :intents, only: [] do
      get 'report'
      post 'import'
      get 'export'
    end
  end

  resources :clips, only: %i(show edit update destroy)

  resources :clip_memberships, only: %i(update destroy)

  resources :groups, controller: 'drawless_groups' do
    member do
      put 'lock'
      put 'unlock'
    end
    resource :suite_assignment, only: %i(new create destroy)
    resource :room_assignment, only: %i(new create edit) do
      collection do
        get 'confirm'
      end
    end
  end

  resource :email_export, only: %i(new create)

  resources :results, only: [] do
    collection do
      get 'students'
      get 'suites'
      get 'export'
    end
  end
end

app/controllers/intents_controller.rb
# frozen_string_literal: true

# Controller for Intents
class IntentsController < ApplicationController
  prepend_before_action :set_draw

  def report
    @intents_importer = IntentsImportForm.new(students: nil)
    @students_by_intent = UsersByIntentQuery.new(@draw.students).call
    @intent_metrics = @students_by_intent.transform_values(&:count)
  end

  def import
    result = IntentsImportForm.import(students: @draw.students,
                                      file: intents_import_params['file'].path)
    handle_action(path: report_draw_intents_path(@draw), **result)
  end

  def export
    @students = @draw.students.order(:intent, :last_name)
    attributes = %I[#{User.login_attr} last_name first_name intent]
    result = CSVGenerator.generate(data: @students, attributes: attributes,
                                   name: 'intents')
    handle_file_action(**result)
  end

  private

  def authorize!
    authorize :intent
  end

  def set_draw
    @draw = Draw.includes(:students).find(params[:draw_id])
  end

  def intents_import_params
    params.require(:intents_import_form).permit(:file)
  end
end

app/views/intents/_intent_form.html.erb
<%= simple_form_for user, url: update_intent_user_path(user), remote: :true do |f| %>
  <%= f.input :intent, collection: User.intents.keys, label_method: :humanize, as: :select, input_html: { class: 'autosubmitme' } %>
<% end %>

app/views/intents/report.html.erb
<% provide(:title, "#{@draw.name} - Intent Report" ) %>
<h1 class="draw-name"><%= @draw.name %> - Intent Report</h1>
<% if policy(:intent).import? %>
  <h2>Import Intents</h2>
  <p>If you would like to import the intents for students in this draw
  please upload a CSV file containing the relevant data below. The CSV
  must have the columns "<%= User.login_attr %>,intent" where the
  intent is either "on_campus" or "off_campus"</p>
  <p>
  <%= simple_form_for @intents_importer, url: import_draw_intents_path(@draw) do |f| %>
    <%= f.input :file, label: 'Upload a CSV', as: :file %>
    <%= f.submit 'Import' %>
  <% end %>
<% end %>
<div class="intent-report">
  <p>You can view and update the intents of students <strong>who are not in a group</strong> below. Note that selecting a different option in the dropdown menu will <em>immediately</em> change that student's intent.</p>
  <hr />
  <% if @students_by_intent.empty? %>
    <p>There are no students in this draw yet!</p>
  <% else %>
    <ul class="tabs" data-tabs id="student-intent-tabs">
      <% @intent_metrics.each do |intent, count| %>
        <li class="tabs-title<%= @intent_metrics.keys.first == intent ? ' is-active' : '' %>">
        <a href="#students-<%= intent %>"<%= @intent_metrics.keys.first == intent ? ' aria-selected=true' : '' %>><%= "#{intent.humanize} (#{count})" %></a>
        </li>
      <% end %>
    </ul>
    <div class="tabs-content" data-tabs-content="student-intent-tabs">
      <% @intent_metrics.each do |intent, count| %>
        <div class="tabs-panel<%= @intent_metrics.keys.first == intent ? ' is-active' : '' %>" id="students-<%= intent %>">
          <h2><%= intent.humanize %> (<%= pluralize(count, 'student') %>)</h2>
          <table>
            <thead>
              <tr>
                <td>Last Name</td>
                <td>First Name</td>
                <td>Intent</td>
              </tr>
            </thead>
            <tbody>
              <% @students_by_intent[intent].each do |student| %>
                <tr class="<%= student.intent %>">
                  <td data-role="student-last_name"><%= student.last_name %></td>
                  <td data-role="student-first_name"><%= student.first_name %></td>
                  <% if policy(student).update_intent? %>
                    <td class="intent-form" id="intent-form-<%= student.id %>" data-role="student-intent"><%= render 'intent_form', user: student %></td>
                  <% else %>
                    <td data-role="student-intent"><%= student.intent.humanize %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </ul>
  <% end %>
</div>
<div style="padding-top: 1em;"><%= link_to 'Export to CSV', export_draw_intents_path(@draw), class: 'button secondary' %></div>
<%= link_to 'Return to draw', draw_path(@draw) %>