config/routes.rb
# frozen_string_literal: true

# rubocop:disable BlockLength
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :suites
    resources :colleges
    resources :buildings
    resources :draws
    resources :groups
    resources :memberships
    resources :rooms

    root to: 'users#index'
  end

  devise_for :users
  unauthenticated :user do
    root to: 'high_voltage/pages#show', id: 'home', as: 'landing_page'
  end
  root to: 'dashboards#show'

  resources :colleges, only: %i(index new create show edit update)

  shallow do
    resources :buildings do
      resources :suites, except: :index do
        member do
          get 'merge'
          post 'merge', to: 'suites#perform_merge'
          get 'split'
          post 'split', to: 'suites#perform_split'
          post 'unmerge'
        end
        resources :rooms, except: :index
      end
    end
  end

  post 'suite_import/import', to: 'suite_imports#import', as: 'suite_import'

  resource :terms_of_service, only: %i(show) do
    patch 'accept'
  end

  resources :users do
    member do
      get 'intent', to: 'users#edit_intent', as: 'edit_intent'
      patch 'intent', to: 'users#update_intent', as: 'update_intent'
    end

    collection do
      get 'build'
    end
  end

  resources :enrollments, only: %i(new create)

  resources :draws do
    member do
      patch 'activate'
      post 'reminder'
      patch 'bulk_on_campus'
      get 'students', to: 'draws#student_summary', as: 'student_summary'
      patch 'students', to: 'draws#students_update', as: 'students_update'
      get 'lottery_confirmation'
      patch 'start_lottery'
      get 'oversubscription', to: 'draws#oversubscription', as: 'oversub'
      patch 'size_lock/:size', to: 'draws#toggle_size_lock',
                               as: 'toggle_size_lock'
      patch 'lock_all_sizes'
      delete 'prune_oversub/:prune_size', to: 'draws#prune', as: 'prune'
      patch 'start_selection'
      get 'results'
      get 'group_export'
    end

    resources :draw_suites, only: %i(index), as: :suites do
      collection do
        get 'edit_collection'
        patch 'update_collection'
      end
    end

    resources :lottery_assignments, only: %i(update create index) do
      collection do
        post 'automatic'
      end
    end

    resources :groups do
      member do
        post 'request', to: 'groups#request_to_join'
        put 'accept_request'
        get 'invite'
        patch 'invite', to: 'groups#send_invites', as: 'send_invites'
        put 'accept_invitation'
        put 'reject_pending'
        put 'finalize'
        put 'finalize_membership'
        put 'lock'
        put 'unlock'
        delete 'leave'
        patch 'make_drawless'
      end
      collection do
        resource :suite_assignment, only: %i(new create destroy)
      end
    end

    resource :clip, only: %i(new create)

    resource :intents, only: [] do
      get 'report'
      post 'import'
      get 'export'
    end
  end

  resources :clips, only: %i(show edit update destroy)

  resources :clip_memberships, only: %i(update destroy)

  resources :groups, controller: 'drawless_groups' do
    member do
      put 'lock'
      put 'unlock'
    end
    resource :suite_assignment, only: %i(new create destroy)
    resource :room_assignment, only: %i(new create edit) do
      collection do
        get 'confirm'
      end
    end
  end

  resource :email_export, only: %i(new create)

  resources :results, only: [] do
    collection do
      get 'students'
      get 'suites'
      get 'export'
    end
  end
end

app/models/drawless_group.rb
# frozen_string_literal: true

# Delegator class to allow for different permissions through Pundit for the
# SpecialGroupsController.
class DrawlessGroup < SimpleDelegator
  # Specify the alternative policy for special groups for Pundit
  def self.policy_class
    DrawlessGroupPolicy
  end
end

app/controllers/drawless_groups_controller.rb
# frozen_string_literal: true

# Controller class for 'special' (admin-created outside of draw) housing groups.
class DrawlessGroupsController < ApplicationController
  prepend_before_action :set_group, except: %i(new create index)
  before_action :set_form_data, only: %i(new edit)

  def show
    if @group.draw.present?
      redirect_to(draw_group_path(@group.draw, @group)) && return
    end
    generate_suites_data

    render layout: 'application_with_sidebar'
  end

  def index
    @groups_by_size = Group.where(draw_id: nil).order(:size).group_by(&:size)
    @sizes = @groups_by_size.keys
  end

  def new; end

  def create
    result = DrawlessGroupCreator.create(params: drawless_group_params)
    @group = result[:record]
    set_form_data unless result[:redirect_object]
    handle_action(action: 'new', **result)
  end

  def edit; end

  def update
    result = DrawlessGroupUpdater.update(group: @group,
                                         params: drawless_group_params)
    @group = result[:record]
    set_form_data unless result[:redirect_object]
    handle_action(action: 'edit', **result)
  end

  def destroy
    result = Destroyer.destroy(object: @group, name_method: :name)
    handle_action(path: groups_path, **result)
  end

  def lock
    result = GroupLocker.lock(group: @group)
    handle_action(path: group_path(@group), **result)
  end

  def unlock
    result = GroupUnlocker.unlock(group: @group)
    handle_action(path: group_path(@group), **result)
  end

  private

  def authorize!
    @group ? authorize(DrawlessGroup.new(@group)) : authorize(DrawlessGroup)
  end

  def drawless_group_params
    p = params.require(:group).permit(:size, :leader_id, :transfers,
                                      member_ids: [], remove_ids: [])
    return p if @group
    p.reject! { |k, _v| k == 'transfers' }
  end

  def set_group
    @group = Group.includes(:members).find(params[:id])
  end

  def set_form_data
    @group ||= Group.new
    @students = UngroupedStudentsQuery.call
    @leader_students = @group.members.empty? ? @students : @group.members
    @suite_sizes = SuiteSizesQuery.call
  end

  def generate_suites_data
    @compatible_suites = CompatibleSuitesQuery.call(@group).order(:number)
    @compatible_suites_no_draw =
      @compatible_suites.select { |s| s.draws.empty? }.group_by(&:building)
    @compatible_suites_in_draw =
      @compatible_suites.select { |s| s.draws.present? }.group_by(&:building)
  end
end

app/views/drawless_groups/_actions.html.erb
<%= link_to 'View', group_path(group), class: 'button' %>
<% if policy(group).edit? %>
  <%= link_to 'Edit', edit_group_path(group), class: 'button' %>
<% end %>
<% if policy(group).destroy? %>
  <%= link_to 'Disband', group_path(group), method: :delete, data: { confirm: 'Are you sure you want to disband this group?' }, class: 'button alert' %>
<% end %>

app/views/drawless_groups/_form.html.erb
<%= simple_form_for @group do |f| %>
  <%= render partial: 'groups/form_fields', locals: { f: f } %>
<% end %>

app/views/drawless_groups/edit.html.erb
<% provide(:title, 'Edit Special Group') %>
<h1>Edit <%= @group.name %></h1>
<%= render 'form', group: @group %>
<%= link_to 'Cancel', group_path(@group) %>

app/views/drawless_groups/index.html.erb
<% provide(:title, 'All Special Groups') %>
<h1>Special Groups</h1>
<h2 class="h3">Summary</h2>
<div class="group-report">
  <%= render 'draws/group_report', sizes: @sizes, groups: @groups_by_size,
                                   actions_partial: 'drawless_groups/actions',
                                   path: groups_path, diff: nil, group_counts: nil,
                                   suite_counts: nil %>
</div>
<hr />
<% if policy(DrawlessGroup).new? %>
  <%= link_to 'New Special Group', new_group_path, class: 'button secondary' %>
<% end %>

app/views/drawless_groups/new.html.erb
<% provide(:title, 'Add Special Group') %>
<h1>Add Special Group</h1>
<%= render 'form', group: @group %>
<%= link_to 'Cancel', groups_path %>

app/views/drawless_groups/show.html.erb
<% provide(:title, @group.name) %>
<%= render 'groups/group_details', group: @group %>
<% if policy(DrawlessGroup.new(@group)).select_suite? %>
  <% if @group.suite.present? %>
    <dl>
      <dt>Suite</dt>
      <dd><%= @group.suite.name %></dd>
    </dl>
    <%= link_to 'Remove suite', group_suite_assignment_path(@group), method: :delete, class: 'button alert' %>
  <% else %>
    <%= link_to 'Assign suite', new_group_suite_assignment_path(@group), class: 'button' %>
  <% end %>
<% end %>
<hr />
<div>
  <%= link_to 'Edit', edit_group_path(@group), class: 'button secondary' if policy(@group).edit? %>
  <% if policy(@group).lock? %>
    <%= link_to 'Lock Group', lock_group_path(@group), method: :put, class: 'button alert' %>
  <% end %>
  <% if policy(@group).unlock? %>
    <%= link_to 'Unlock All Members', unlock_group_path(@group), method: :put, class: 'button alert' %>
  <% end %>
  <% if policy(@group).assign_rooms? %>
    <%= link_to 'Assign rooms', new_group_room_assignment_path(@group), class: 'button' %>
  <% end %>
  <% if policy(@group).edit_room_assignment? %>
    <%= link_to 'Edit room assignments', edit_group_room_assignment_path(@group), class: 'button' %>
  <% end %>
  <%= link_to('Disband', group_path(@group), method: :delete, data: { confirm: 'Are you sure you want to disband this group?' }, class: 'button alert') if policy(@group).destroy? %>
</div>

<%= link_to 'View all special groups', groups_path %>

<% content_for :sidebar do %>
  <h1 class="h3">Compatible Suites</h1>
  <p class="h4">
    <%= @compatible_suites.count %> available
    <%= size_str(@group.size).capitalize.pluralize(@compatible_suites.count) %>
  </p>
  <% unless @compatible_suites_no_draw.count.zero? %>
    <h2 class="h4">Not in Any Draw</h2>
    <%= render 'groups/suites_table', suites: @compatible_suites_no_draw %>
  <% end %>
  <% unless @compatible_suites_in_draw.count.zero? %>
    <h2 class="h4">In Draw(s)</h2>
    <%= render 'groups/suites_table', suites: @compatible_suites_in_draw %>
  <% end %>
<% end %>